pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Backend') {
            steps {
                dir('user') {          // 👈 IMPORTANT
                    sh 'mvn clean package'
                }
            }
        }
    }

    post {
        success {
            echo 'Backend build successful ✅'
            archiveArtifacts 'user/target/*.jar'
        }
        failure {
            echo 'Backend build failed ❌'
        }
    }
}
